name: hack_mobile

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'  
  image_picker: ^0.6.0+10
  flutter_bloc: ^0.13.0
  path_provider: ^0.5.0+1
  sembast: ^1.15.4
  page_transition: ^1.1.0
  permission_handler: ^3.1.0
  flare_flutter: ^1.5.0
  auto_size_text: ^2.0.1
  flutter_ffmpeg: ^0.2.3
  video_player: ^0.10.1+3
  flutter_range_slider: ^1.3.0
  share_extend: "^1.0.9"
  


dev_dependencies:

flutter:
  uses-material-design: true
  assets:
    - assets/bg.png
    - assets/animations/success.flr